sudo: required

services:
- docker

language: cpp
dist: xenial
os: linux

git:
  autocrlf: false

addons:
  apt:
    sources:
      - sourceline: 'deb http://dl.bintray.com/igagis/ubuntu xenial main'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x379CE192D401AB61'
    update: true
    packages:
    - binfmt-support
    - qemu-user-static
    - myci
  homebrew:
    update: true
    taps:
    - igagis/tap
    packages:
    - myci

matrix:
  include:
    - name: macosx
      os: osx
      compiler: clang
      osx_image: xcode11
    - name: ios
      os: osx
      compiler: clang
      osx_image: xcode11
    - name: android
      language: android
      android:
        components:
          - platform-tools
          - tools
          - build-tools-28.0.3
          - android-28
#          - sys-img-armeabi-v7a-android-22
          - extra-android-m2repository
    - name: msys2
      os: windows


env:
  global:
  # Encrypted MYCI_BINTRAY_API_KEY for publishing to bintray.
  - secure: "DszGTHBC8zncsnSUZnXhVW0Yp+ImvSlZNxmIzhHjOb1Pa/lrp5mHFGWWK7OP52tiGOKE+QN4XdZCTSbUPcOP+d/PjE3PEqLEqYmDdhKw6c0OcbW9HQXKSZkRkjhjBNtV2cm0ifCJPfha1xi58BWgPJHfNuPslWF4dr8B/ZW8MJoAulS/4ASTAKCCI1B/FmUZlorCmM0cEerb3444t/Xc7RpO8EhJLl0FG9K3JiPBnjSQS/uvPEJqF8mxSl4q5Puul2yhcynLmC+o94Do3++dtMZYSDRjkyDE6Gh1JkHwfRI/YPg1X6UjmMNLvs+F2aDM/LguxJFC0yEHYHFjuVp8z44n6WHMNbLQLQAnVijhRHL0lSrAPcciStMauL7ld7bJk4G1G7y7i9D6GgG9e+Ov2nN9Nd/m1BIZQ8B6fE9NYbM3e5qAiZmQtK3h/g/WQV8X52scQrgUeg5PcpaS3vkjCoAauGFgZj9hoUvfw8rxtqhS8kNw8gUr/DI3ZtwClRoS9uk8Y4J/lOb6xA7NBzm/rRO1MFXLkXBI54ZeN+wHNN+PGcAIX6dDdG+CaWfUIC7/I2OkvjAuLF4qzQgVyFw7UBH3P6n1zBgNR+rOHGfZDBI4QEjNxDTvvzBoAiqOldqL7+S9Kw/DTNR2zNUTXI1+khgqb/yZGdqW1+BcaU65Qyg="
  # Encrypted MYCI_GIT_ACCESS_TOKEN for publishing to homebrew-tap and cocoapods.
  - secure: "aPOQQi/TEzk4DhdR/Yq8BrhLriDEfkh2/MALOXYAZId0vX8irxsKXMJs1wpy0+elsbbu9WQdyKux/DcoqG9GCW65KBQhoict1amo9Bth1VCjYOuaDy3aOSpLX/QtafokPSyMZCDfTFqjhjWQKNxWEjaN0F4CoILfJEaaOZoUE6ERBTuK3ebuAmCaUUIJJntLF02+w126dQE0VMbFyvZ/yGHy9mFtRPSaSEEzcGJt5knU3ZWzVgtQsK+oKf8Vr4yxs2immSrGF7BDkxVLUdJ+iL8fZzeNOemTMztEyfVmeMnvsNzwoB1DBZ554nzTi/bVEr+tkFIHhzUyOOSZGgN8sTZTt91eo9mDBfVyDqc6mE7NIc7+ChTUGcyeFXDBidkGTmjy6orNEpitdQ1k5RUb9L14HLK1TBaWC6L6WOfRmGfUAbAPrOAVblTfHtNRFmIq8CNYmT7JtBddr6/foECuP0c1fTY1xjN2keR4nFSPOtJ3JHoaYXfnZ8ilFlYGFsWRGOBHMPJ8JG4nCcNvrX8/KbvIBlaDSWKEOp+Haqu556W82ffuWp0Exm+sasxn1htKZERVKP/IUplv4QWM003O64eqBk8NsR44BiXlt133GUY4iQJ2b2vVNNXUocBihDX70WcG4sUNjyVNWgSMFXO5msp+NulkhOHtk0ylruubxoI="
  - MYCI_GIT_USERNAME=igagis
  - PACKAGE_NAME=audout
  matrix:
  - OS_REL=xenial OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=bionic OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=buster OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=raspbian DOCKER_IMAGE=igagis/$OS:$OS_REL PACKAGE_TYPE=deb

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker run --name ccc -v $TRAVIS_BUILD_DIR/..:/build -w /build/$(basename $TRAVIS_BUILD_DIR) -it -d $DOCKER_IMAGE bash &&
    if [ "$PACKAGE_TYPE" == "deb" ]; then
      docker exec ccc apt update &&
      docker exec ccc apt install -y dirmngr &&
      docker exec ccc bash -c "echo 'deb http://dl.bintray.com/igagis/$OS $OS_REL main' > /etc/apt/sources.list.d/igagis.list" &&
      docker exec ccc apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
      docker exec ccc apt update &&
      docker exec ccc apt install -y devscripts equivs myci &&
      myci-deb-prepare.sh;
    fi;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    brew install prorab prorab-extra libutki libnitki;
  fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    sudo gem install cocoapods &&
    pod repo add --silent igagis https://$PRORAB_GIT_USERNAME:$PRORAB_GIT_ACCESS_TOKEN@github.com/igagis/cocoapods-repo.git &&
    pod install --project-directory=xcode;
  fi
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    choco upgrade --no-progress -y msys2 &&
    export msys2="/c/tools/msys64/msys2_shell.cmd -defterm -no-start -msys -here -c" &&
    $msys2 "echo -e '[igagis_msys]\\nSigLevel = Optional TrustAll\\nServer = https://dl.bintray.com/igagis/msys2/msys' >> /etc/pacman.conf" &&
    $msys2 "echo -e '[igagis_mingw64]\\nSigLevel = Optional TrustAll\\nServer = https://dl.bintray.com/igagis/msys2/mingw64' >> /etc/pacman.conf" &&
    $msys2 "echo -e '[igagis_mingw32]\\nSigLevel = Optional TrustAll\\nServer = https://dl.bintray.com/igagis/msys2/mingw32' >> /etc/pacman.conf" &&
    $msys2 "pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade" &&
    $msys2 "pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade" &&
    $msys2 "pacman -Sy --noconfirm myci mingw-w64-x86_64-toolchain mingw-w64-i686-toolchain";
  fi
- if [ "$TRAVIS_OS_NAME" == "linux" ] || [ "$TRAVIS_OS_NAME" == "osx" ]; then
    export PACKAGE_VERSION=$(myci-deb-version.sh debian/changelog);
  fi

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc myci-deb-install-build-deps.sh;
  fi
# Accept android SDK licenses and install android tools
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    echo y | sdkmanager "ndk-bundle" &&
    echo y | sdkmanager "cmake;3.6.4111459";
  fi

before_script:
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    curl -L https://github.com/zackslash/Xcode-Proj-Adder/raw/master/bin/XcodeProjAdder -O &&
    chmod +x XcodeProjAdder &&
    (cd xcode/$PACKAGE_NAME && ../../XcodeProjAdder -XCP $PACKAGE_NAME.xcodeproj -SCSV `echo $(find ../../src -type f -name *.cpp) | sed -E -e 's/ /,/g'`)
  fi
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    $msys2 "myci-apply-version.sh -v \$(myci-deb-version.sh debian/changelog) msys2/PKGBUILD.in";
  fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc dpkg-buildpackage -us -uc;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    make &&
    make test;
  fi
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    xcodebuild -workspace xcode/$PACKAGE_NAME.xcworkspace -scheme $PACKAGE_NAME CONFIGURATION_BUILD_DIR=../build -configuration Release &&
    myci-create-zip-package.sh -h src -f xcode/build/lib$PACKAGE_NAME.a///lib/ios -f LICENSE $PACKAGE_NAME-$PACKAGE_VERSION.zip;
  fi
- if [ "$TRAVIS_JOB_NAME" == "android" ]; then
    (cd android && ./gradlew build) &&
    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.pom.in &&
    myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` android/*.aar.in --filename-only;
  fi
# running MSYS2 script from deployment provider did not work for some reason, so we do it here if the commit is a tagged one.
- if [ "$TRAVIS_JOB_NAME" == "msys2" ]; then
    $msys2 "(cd msys2 && makepkg-mingw --syncdeps --noconfirm --skipinteg)" &&
    if [ ! -z "$TRAVIS_TAG" ]; then
      $msys2 "myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw64 -d igagis_mingw64 msys2/mingw-w64-x86_64-*-any.pkg.tar.xz" &&
      $msys2 "myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw32 -d igagis_mingw32 msys2/mingw-w64-i686-*-any.pkg.tar.xz";
    fi;
  fi


before_deploy:
  - myci-apply-version.sh -v `myci-deb-version.sh debian/changelog` travis_bintray_*.json.in

deploy:
- provider: script
  skip_cleanup: true
  on:
    tags: true
    condition: $PACKAGE_TYPE = deb && -z "$TRAVIS_JOB_NAME"
  script: myci-deploy-debian-bintray.sh -u igagis -r $OS -p $PACKAGE_NAME -c main -d $OS_REL $TRAVIS_BUILD_DIR/../*.deb
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = android
  file: travis_bintray_android.json
  user: igagis
  key:
    secure: "hM788IuVegYWTiV9tzrWHbh1dyZv4mE8Nq+hE7W8ReZ1Lp5wsW50PCg4pZE1BcZrA69C5pPmUcqNBB7RcV+Ip2WszTKNH/gNWMtKx3PYSuca3yJX8seO4hNMKLvImH7BYpOz4GP4rjonSXRu752Uf4uMjzTCW1KS4FSQhne3bI+DKHcjC64tQlguOwk7LtTPK/P972tNltTHnK14dJm+4JEmZdtppvFdeCtb4j3+KgYuV+fdO3ztg6eHgqMvr6Qq9CXNKVC8X+pQRjw7sRHqgwweycOJLPxLrjI9Hv3RpFD2h+HqI56sJWX0u5BwMkE7v4lpZlWGB1dII7FM5jgGHuyovWNNxCZgjmUKwMcJQQ2rN/TUhaQolgeiV/sXbVCKCy2smgx1Rt+SajQvnAKwkU78rlYAF2dej4UYLeyxI76B6JNR92VqK9rY7yA+tbok7xCEyyfQp5cfD3AfL/hXY0/DDMVFRDI0WegUQTPOnIgdLtU8jKTXK0XlCs0hj74jCIEwmr7LgK65K+H0ZgYGJNzUwHay8hDUHFfCtlF4ClY8ypYVAMRxmU2cNoxLCo+vc8sk4qeVd6aAVdJDmBhK1Bz0jx4isBj561PissrCVocQYJypKPIpj2eMBo8Im6nyVTRpQd5gyBzUcr/sWgY+RpM+qRqGShQKl9nzPceO9xc="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: myci-deploy-homebrew.sh -t igagis/tap homebrew/libaudout.rb.in
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = macosx
- provider: script
  skip_cleanup: true
  script: myci-deploy-cocoapods.sh -r igagis -v $PACKAGE_VERSION -u igagis -b cocoapods -p $PACKAGE_NAME-$PACKAGE_VERSION.zip cocoapods/$PACKAGE_NAME.podspec.in
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = ios

